# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Hatrung8888-
  host: localhost

development:
  <<: *default
  database: bookingticket_development

test:
  <<: *default
  database: bookingticket_test

production:
  <<: *default
  database: bookingticket_production
